Update patch set 5
Patch Set 5: Code-Review-1

> IOError: [Errno 2] No such file or directory: 'docs.sh'

I need to find and fix errors.

Patch-set: 5
Label: Code-Review=-1