Update patch set 4
Patch Set 4:

Looks like openssl-devel is missing for aarch64 centos-8 stable/2009:
/scratch/docker-build/vpp/build/external/rpm/tmp/dpdk-20.08/drivers/crypto/qat/qat_sym.c:5:10: fatal error: openssl/evp.h: No such file or directory

I think this worked before - what's changed?

Patch-set: 4
Reviewer: Gerrit User 576 <576@6d2eb258-4fe2-443e-8a38-ca81da23d4c2>